<?php echo $header; ?>
<!-- Main Content -->
<main>
<!-- Agreement -->
<div class="panel agreement">
	<h1 class="heading-1">Szabadulj ki a fürdőszobából és nyerd meg az értékes Möve&Zwilling nyeremények egyikét!</h1>
	<p class="paragraph-1">Ha eddig még nem tetted, lájkold az oldalunkat ajánlatainkért és nyereményjátékainkért!</p>
	<div class="checkbox">
		<input type="checkbox" id="checkboxG1" class="css-checkbox"><label for="checkboxG1" class="css-label">Feliratkozom a SPAR Hírlevélre.</label>
	</div>
	<div class="checkbox">
		<input type="checkbox" id="checkboxG2" class="css-checkbox"><label for="checkboxG2" class="css-label wrong">Elfogadom a <a target="_blank" href="#">játékszabályzatot.</a></label>
	</div>
	<button class="btn-purple">Tovább</button>
</div>
<!-- Description -->
<div class="panel description">
	<h1 class="heading-1">Fejtsd meg legalább 7 feladványunkat és szabadulj ki a fürdőszobából!</h1>
	<p class="paragraph-1">Minél több feladányt fejtesz meg, annál nagyobb az esélyed az értékes Möve & Zwilling nyeremények megnyerésére.</p>
	<h2>Minden nap új rejtvény!</h2>
	<div class="locker">
		<span>7x</span>
		<div class="padlock"></div>
	</div>
	<button class="btn-purple">Játszom</button>
</div>
<!-- Game -->
<div class="panel game">
	<div class="popup game-1">
		<div class="selected-product">
			<img src="/<?php echo $this->config->rootDir; ?>/upload/images/game/1.png" alt="Mosdó Kagyló">
		</div>
		<h1 class="number">1.</h1>
		<p>Tippeld meg mekkora az egy főre jutó vízfogyasztás!</p>
		<div class="answers">
			<button class="btn-green answer-1">5-6 köbméter</button>
			<button class="btn-red answer-2">2-3 köbméter</button>
			<button class="btn-purple-2 answer-3">7-8 köbméter</button>
		</div>
	</div>
	<div class="game-box">
		<div class="navigations">
			<a href="#" class="left"></a>
			<a href="" class="right"></a>
		</div>
	</div>
	<div class="lockers">
		<div class="row">
			<div class="line one">
				<?php
					for ($i=0; $i < 7 ; $i++) {
				?>
				<div class="lock"></div>
				<?php
				}
				?>
			</div>
			<div class="line two">
				<?php
					for ($i=0; $i < 7 ; $i++) {
				?>
				<div class="lock active"></div>
				<?php
				}
				?>
			</div>
		</div>
		<div class="row">
			<div class="line three">
				<?php
					for ($i=0; $i < 7 ; $i++) {
				?>
				<div class="lock"></div>
				<?php
				}
				?>
			</div>
		</div>
	</div>
</div>
<!-- Success -->
<div class="panel success">
	<h1 class="heading-1">Gratulálunk!</h1>
	<p class="paragraph-1">Sikeresen megfejtetted a mai feladatot, ezzel is közelebb kerültél a kiszabaduláshoz. Gyere vissza holnap is, mert 7 helyes megoldással kerülsz be az első sorsolásba!</p>
	<div class="share">
		<p>Adj esélyt barátaidnak is a nyerésre, oszd meg a játékot!</p>
		<button class="btn-purple">Megosztom</button>
	</div>
	<div class="give">
		<p>Add meg adataidat, hogy értesíteni tudjunk nyereményedről, amennyiben a kisorsolt nyertesek között leszel!</p>
		<button class="btn-purple">Megadom</button>
	</div>
</div>
<!-- Success Draw -->
<div class="panel success-draw">
	<h1 class="heading-1">Gratulálunk!</h1>
	<p class="paragraph-1">Sikeresen megfejtetted ma is a feladatot, kiszabadultál a fürdőszobából, ezzel be is kerültél az első sorsolási szintbe. Gyere vissza holnap is, hogy elérd a következő sorsolási szintet!</p>
	<div class="share">
		<p>Adj esélyt barátaidnak is a nyerésre, oszd meg a játékot!</p>
		<button class="btn-purple">Megosztom</button>
	</div>
	<div class="give">
		<p>Add meg adataidat, hogy értesíteni tudjunk nyereményedről, amennyiben a kisorsolt nyertesek között leszel!</p>
		<button class="btn-purple">Megadom</button>
	</div>
</div>
<!-- Fail -->
<div class="panel fail">
	<h1 class="heading-1">Ez sajnos most nem talált.</h1>
	<p class="paragraph-1">Ne csüggedj, holnap új feladattal várunk, így újra esélyed lesz a kiszabadulásra!</p>
	<p class="give-chance">Adj esélyt barátaidnak is a nyerésre, oszd meg a játékot!</p>
	<button class="btn-purple">Megosztom</button>
</div>
<!-- Fail 2-->
<div class="panel fail-2">
	<h1 class="heading-1">Ez sajnos most nem talált.</h1>
	<p class="paragraph-1">Játssz újra, mert ma még megoldhatod az összes feladatot, hogy bekerülj a sorsolásba!</p>
	<p class="give-chance">Adj esélyt barátaidnak is a nyerésre, oszd meg a játékot!</p>
	<button class="btn-purple">Megosztom</button>
</div>
<!-- Fail Draw-->
<div class="panel fail-draw">
	<h1 class="heading-1">Ez sajnos most nem talált.</h1>
	<p class="paragraph-1">De már kiszabadultál a fürdőszobából és elérted az első sorsolási szintet.</p>
	<p class="paragraph-1">Ne csüggedj, holnap is játszhatsz, így újra esélyed nyílik a következő sorsolási szint elérésére!</p>
	<p class="give-chance">Adj esélyt barátaidnak is a nyerésre, oszd meg a játékot!</p>
	<button class="btn-purple">Megosztom</button>
</div>
<!-- Game Over -->
<div class="panel game-over">
	<h1 class="heading-1">Játék véget ért, köszönjük, hogy velünk játszottál!</h1>
	<p class="paragraph-1">A sorsolás eredményét 2016. június 15-én este 6 óráig tesszük közzé.</p>
	<p class="paragraph-1">A nyerteseket e-mailben fogjuk értesíteni a további teendőikről.</p>
</div>
<!-- Winners -->
<div class="panel winners">
	<div class="top">
		<h1 class="heading-1">Köszönjük, hogy velünk játszottál!</h1>
		<p class="paragraph-1">Gratulálunk a nyerteseknek:<br>A játék lezárást követő 10 napon belül e-mailben értesítjük nyerteseinket a további teendőkről. </p>
	</div>
	<div class="bottom">
		<div class="tabs">
			<button class="prize-1 btn-purple active">Nyeremény 1</button>
			<button class="prize-2 btn-purple">Nyeremény 2</button>
			<button class="prize-3 btn-purple">Nyeremény 3</button>
		</div>
		<div class="names">
			<div class="prize-1">
				<ul>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária</li>
					<li>Tóth Péter</li>
					<li>Báder László</li>
					<li>Szabó Áron</li>
				</ul>
				<ul>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária</li>
					<li>Tóth Péter</li>
					<li>Báder László</li>
					<li>Szabó Áron</li>
				</ul>
			</div>
			<div class="prize-2">
				<ul>
					<li>Tóth Péter</li>
					<li>Báder László</li>
					<li>Szabó Áron</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária</li>
				</ul>
				<ul>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária</li>
					<li>Tóth Péter</li>
					<li>Báder László</li>
					<li>Szabó Áron</li>
				</ul>
			</div>
			<div class="prize-3">
				<ul>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Szabó Áron</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária</li>
					<li>Tóth Péter</li>
				</ul>
				<ul>
					<li>Kovács Annamária Zsuzsanna</li>
					<li>Kovács Annamária</li>
					<li>Báder László</li>
					<li>Tóth Péter</li>
					<li>Báder László</li>
					<li>Szabó Áron</li>
				</ul>
			</div>
		</div>
	</div>
</div>
</main>
<?php echo $footer; ?>