<?php echo $header; ?>
<!-- Main Content -->
<main>
	<!-- Description -->
	<div class="panel description">
	</div>
	<!-- Agreement -->
	<div class="panel agreement">
		<h1 class="heading-1">Szabadulj ki a fürdőszobából és nyerd meg az értékes Möve&Zwilling nyeremények egyikét!</h1>
		<p class="paragraph-1">Ha eddig még nem tetted, lájkold az oldalunkat ajánlatainkért és nyereményjátékainkért!</p>
	</div>
	<!-- Vote -->
	<div class="panel vote">
	</div>
	<!-- Thanks for vote -->
	<div class="panel thanks">
	</div>
	<!-- Already voted -->
	<div class="panel voted">
	</div>
	<!-- Game Description -->
	<div class="panel game-description">
	</div>
	<!-- Game -->
	<div class="panel game">
	</div>
	<!-- Success -->
	<div class="panel success">
	</div>
	<!-- Fail -->
	<div class="panel fail">
	</div>
	<!-- Game Over -->
	<div class="panel game-over">
	</div>
	<!-- Winners -->
	<div class="panel winners">
	</div>
</main>
<?php echo $footer; ?>